### ISSUE TITLE
Question - is this still usable?

### ISSUE THREAD

**Issue by bryllyg** [SPCSR/HelperFunctions#10]
It's been a while since this has been updated. I'm just wondering with all the updates to search over the last year or so, is this still a viable synonym solution? If so, can this be used to manage a single synonym list to be used across multiple sites or the tenant?
Thanks!

**Comment by wobba** [comment]
Only for classic search experiences.

**Comment by bryllyg** [comment]
Thanks for the clarification, that's what I was suspecting.
