### ISSUE TITLE
Error on page load

### ISSUE THREAD

**Issue by svarukala** [SPCSR/HelperFunctions#4]
Hi!
I added search box, search results web part and script reference to my page. I configured things like said in guidance. When page then script is also loaded and on console I can see the following error: 

Uncaught TypeError: Cannot read property 'prototype' of undefined
    at Search.VariableInjection.Search.VariableInjection (search.queryVariableInjector.js:102)
    at spcsr.Search.spcsr.Search (search.queryVariableInjector.js:442)
    at spcsr (search.queryVariableInjector.js:443)
    at Object.<anonymous> (search.queryVariableInjector.js:444)
    at __webpack_require__ (search.queryVariableInjector.js:20)
    at search.queryVariableInjector.js:40
    at search.queryVariableInjector.js:43

**Comment by svarukala** [comment]
Go around the issue by encompassing it using SP.SOD.executeFunc()
```
var _origExecuteQuery;
var _origExecuteQueries;
			
SP.SOD.executeFunc("SP.js", "SP.ClientContext", function () {
SP.SOD.executeFunc("SP.Search.js", "Microsoft.SharePoint.Client.Search.Query.KeywordQuery", function () {
				 _origExecuteQuery = Microsoft.SharePoint.Client.Search.Query.SearchExecutor.prototype.executeQuery;
	             _origExecuteQueries = Microsoft.SharePoint.Client.Search.Query.SearchExecutor.prototype.executeQueries;
				});
				});

//var _origExecuteQuery = Microsoft.SharePoint.Client.Search.Query.SearchExecutor.prototype.executeQuery;
//var _origExecuteQueries = Microsoft.SharePoint.Client.Search.Query.SearchExecutor.prototype.executeQueries;
```

**Comment by wobba** [comment]
@estruyf I believe the setting of those should happen inside hookCustomQueryVariables with a executefunc, to ensure the right page flow. Setting them at the top of the module makes them execute too early.

**Comment by estruyf** [comment]
@wobba using executeFunc would cause a problem in loading the results as the web part expect to execute the function. Instead, I moved the initialization of the variables to the hookCustonQueryVariables function.

@svarukala I pushed a fix, can you check if this is working out for you?

**Comment by wobba** [comment]
@estruyf smart move :) this page orchestration in the lifecycle is not easy.

**Comment by svarukala** [comment]
@estruyf  Getting below error with the latest code:

> search.queryVariableInjector.js:3214 Uncaught TypeError: Cannot read property 'prototype' of undefined
>     at Array.hookCustomQueryVariables (search.queryVariableInjector.js:3214)
>     at ScriptResource.axd?d=a_YVqq2-ZjEc3ohxY0mCKaF3MvLXvffrq9qz5OqbZGSC1R33Laym_zzhUs6236nxLCXVHuEC1G0V1n…:5
>     at Sys._Application._raiseInit (ScriptResource.axd?d=a_YVqq2-ZjEc3ohxY0mCKaF3MvLXvffrq9qz5OqbZGSC1R33Laym_zzhUs6236nxLCXVHuEC1G0V1n…:5)
>     at Sys._Application.initialize (ScriptResource.axd?d=a_YVqq2-ZjEc3ohxY0mCKaF3MvLXvffrq9qz5OqbZGSC1R33Laym_zzhUs6236nxLCXVHuEC1G0V1n…:5)
>     at b (ScriptResource.axd?d=a_YVqq2-ZjEc3ohxY0mCKaF3MvLXvffrq9qz5OqbZGSC1R33Laym_zzhUs6236nxLCXVHuEC1G0V1n…:5)
>     at HTMLDocument.a (ScriptResource.axd?d=a_YVqq2-ZjEc3ohxY0mCKaF3MvLXvffrq9qz5OqbZGSC1R33Laym_zzhUs6236nxLCXVHuEC1G0V1n…:5)

Even enclosing those variables in hookCustomQueryVariables with executeFunc is not helping. Enclosing the add_init function with executeFunc is working. Search web part is working just fine and as expected with the synonyms:

```
ExecuteOrDelayUntilBodyLoaded(function () {
                SP.SOD.executeFunc("SP.js", "SP.ClientContext", function () {
                    SP.SOD.executeFunc("SP.Search.js", "Microsoft.SharePoint.Client.Search.Query.KeywordQuery", function () {
                        Sys.Application.add_init(hookCustomQueryVariables);
                    });
                });
            });
```

**Comment by estruyf** [comment]
@svarukala can you go through your setup step by step?

**Comment by svarukala** [comment]
1. Created Publishing site
2. Created the synonyms list, added entries to it
3. Uploaded the search.queryVariableInjector.js to Documents library. Published the file. Copied the link to this file.
4. Added search results, search box and script editor web parts to the page
5. Edited script editor web part to add the script tag to the link from step 3.
6. Configured results web part to replace searchboxquery with synonymquery as documented.
7. Search in the search box and see results in the results web part

**Comment by wobba** [comment]
Did you set the result wp to be run as async, not synchronous mode?

**Comment by svarukala** [comment]
@wobba sorry, I didn't mention that but yes, I set it to async. I pretty much followed the readme steps.

**Comment by wobba** [comment]
@svarukala, @estruyf did some changes - can you try the latest version?

**Comment by svarukala** [comment]
@wobba Just tested the latest version. It works just fine now! Thanks a lot.
