### ISSUE TITLE
Uncaught ReferenceError: Srch is not defined

### ISSUE THREAD

**Issue by metalogique** [SPCSR/HelperFunctions#9]
Hello, 

I packaged / deployed the solution as documented. The {SearchBoxQuery} has been replaced with {SynonymQuery} but in my environment (O365, Publishing site collection) I do not have the Async option: Issue query from the browser option in the Settings so I didn't change that.

![image](https://user-images.githubusercontent.com/25937477/51623357-84d00180-1f06-11e9-9ca7-35cb033b65f8.png)
(in French but the query mode option is not displayed)

When a search query is executed, I get:

![image](https://user-images.githubusercontent.com/25937477/51623317-6b2eba00-1f06-11e9-9236-1b26260f20bb.png)

My guess is that it's a timing issue with Srch but I am unsure on how to fix it. Any idea?

@estruyf ?

**Comment by metalogique** [comment]
The error was mine. Instead of using a CEWP to include the JS reference on the page, I added it to the masterpage using a ScriptLink. Even if the said ScriptLink was at the bottom of the masterpage, it was still being inserted in the HEAD which caused the timing issue. I still include the JS reference in the masterpage but I use a standard Script tag at the bottom of the body.

On a side note, anyone has an explanation for the missing Async option in the Result WP settings in O365?

**Comment by wobba** [comment]
Weird indeed - it used to be there for both search result wp and content search wp I belive. Can you check both?

**Comment by yvsuhas** [comment]
I have the same exact issue as @metalogique as I don't have an option to change the "Loading Behavior" on the "Settings" tab of the search results webpart. I'm also using SPO. So when I replace the {searchboxquery} to {synonymquery}, no results are returned and I'm not sure how to make this script work and even after adding it to the page as the remaining configuration steps are not complete.

**Comment by yvsuhas** [comment]
https://uploads.disquscdn.com/images/83018b48c7f84798dc55b1ae203696b08dae571aa7e02365be0aa25c91d0e4ed.png

**Comment by wobba** [comment]
Async is needed in order for the script to inject, and not sure why it has been removed.

**Comment by yvsuhas** [comment]
> I have the same exact issue as @metalogique as I don't have an option to change the "Loading Behavior" on the "Settings" tab of the search results webpart. I'm also using SPO. So when I replace the {searchboxquery} to {synonymquery}, no results are returned and I'm not sure how to make this script work and even after adding it to the page as the remaining configuration steps are not complete.

I'm able to get it working without having the Loading behavior option in SPO.

**Comment by wobba** [comment]
Seems search wp's are loadig async by default now as I can see the `ProcessQuery` network call.

I added the script and created the Synonyms list and things work just fine
